### ISSUE TITLE
Need help in using v2raya in nixOS

### ISSUE THREAD

**Issue by wthe2004** [iopq/nixos-conf#1]
Hello

I came across your issue on setting up v2rayA on nixOS in the "Issues" section of the [v2rayA/v2rayA](https://github.com/v2rayA/v2rayA) repository. I  wanted to know if you were able to resolve the issue on your nixOS, becasue v2rayA does not work on my machine at all (the browser says no connection). It would be really helpful if you could share any solution or suggestions, or show me your v2rayA part of nix config. Thank you in advance for your assistance.

**Comment by iopq** [comment]
I actually wanted to use it with xray, but v2raya gets confused with what folder it needs to look in for the files

So there are two ways:

1. Install v2raya and use v2ray with it, do a default install of everything
2. Use my NUR package that just deletes the files xray looks in. I call it xraya, but it's buggy because I assume you're using reality and it breaks every other server because it adds fields everywhere that are not necessary

the problem with v2raya is by default it doesn't log the v2ray errors so you see nothing, so you should merge a v2ray config file that sets the error folder to something reasonable on your system - this should be done via a runtime flag

let me know if you need more detailed instructions

**Comment by iopq** [comment]
https://github.com/iopq/nixos-conf/blob/desktop/flake.nix

you can see my flake.nix on how I enable NUR and xraya to use a reality server

**Comment by wthe2004** [comment]
Your configuration did indeed help me, thank you! I unintentionally overlooked checking other branches, haha.
Now it works on my machine.
